// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9tlxyEmX4FD3L6HsKXovDoPkcNBpPvRo',
    appId: '1:13869057578:web:1d7658427c5af1da146553',
    messagingSenderId: '13869057578',
    projectId: 'flutter-crud-a0bba',
    authDomain: 'flutter-crud-a0bba.firebaseapp.com',
    storageBucket: 'flutter-crud-a0bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZGKnt1qUfzr4aczZizL4dtJXQTamMP4',
    appId: '1:13869057578:android:ee5a61a629f7db08146553',
    messagingSenderId: '13869057578',
    projectId: 'flutter-crud-a0bba',
    storageBucket: 'flutter-crud-a0bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOpCeLc7PKHTxaIGgBs-9U8fsNcS8HBDo',
    appId: '1:13869057578:ios:01ff3cd9841dfe80146553',
    messagingSenderId: '13869057578',
    projectId: 'flutter-crud-a0bba',
    storageBucket: 'flutter-crud-a0bba.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOpCeLc7PKHTxaIGgBs-9U8fsNcS8HBDo',
    appId: '1:13869057578:ios:a6f0a1214f2fac18146553',
    messagingSenderId: '13869057578',
    projectId: 'flutter-crud-a0bba',
    storageBucket: 'flutter-crud-a0bba.appspot.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
